services:
    marttiphpbb.datepickerlunar.listener:
        class: marttiphpbb\datepickerlunar\event\listener
        arguments:
            - '@language'
            - '@marttiphpbb.datepickerlunar.calc'
        tags:
            - { name: event.listener }

    marttiphpbb.datepickerlunar.calc:
        class: marttiphpbb\datepickerlunar\util\calc
