services:
    marttiphpbb.datepickerlunar.listener:
        class: marttiphpbb\datepickerlunar\event\listener
        arguments:
            - '@user'
        tags:
            - { name: event.listener }
